### PR TITLE
Fixing the script to handle the new payload format from bitbucket

### PR DESCRIPTION
**Pull request by prudhvi**
Payload format from bitbucket changed and I used this fix in my heroku deploy which works fine.
It also works both on pull request creation and update too :)

Thanks a lot for this nice badge tool, helps me a lot :cake: 

https://confluence.atlassian.com/display/BITBUCKET/Event+Payloads#EventPayloads-PullRequestEvents

@chesleybrown

### CODE REVIEW

**Comment by prudhvi** [comment]
@chesleybrown  PING

**Comment by chesleybrown** [comment]
Interesting. The `pullrequest_created` is still working fine on my current deploy. Are they including both `pullrequest_created` and `pullrequest` in the payload as a backwards compatibility thing?

**Comment by prudhvi** [comment]
Hmm, I definitely don't see `pull_request_created` key in the payload when I viewed the log on heroku(I inserted some console.log stmts). May be they are including both(`pullrequest_created` and `pullrequest`) or just one (`pullrequest_created`) for the old API keys(ie; keys created before certain date).

If you confirm they are sending both for you, I am assuming this is good enough. If they are sending in only old format(`pullrequest_created`) , I can change this PR to support both keys which ever is present.

**Comment by yongjunj** [comment]
I can confirm this issue. Things started working for me after I merged in @prudhvi's patch locally.

**Comment by MarcelEeken** [comment]
I can also confirm this issue, just installed it today and had to make the same changes.

**Comment by chesleybrown** [comment]
Checking the Bitbucket API docs and it says the property is called `pullrequest_created` for the Pull Request POST hook.

https://confluence.atlassian.com/bitbucket/pull-request-post-service-management-385913080.html

Are you "creating" a pull request or just "updating" a pull request?

**Comment by MarcelEeken** [comment]
That is the old hooks, they implemented a new webhooks system https://confluence.atlassian.com/bitbucket/manage-webhooks-735643732.html

**Comment by frankier** [comment]
+1 Ran into this just now. It would be useful to support the current version of the api considering they are threatening to deprecate the old one.

**Comment by chesleybrown** [comment]
Agreed. I will try my best to verify this change and get it merged this week.

**Comment by matteodem** [comment]
what is the status of this?

**Comment by chesleybrown** [comment]
Verified this is the correct fix needed. Merging now.

**Comment by chesleybrown** [comment]
It's also worth mentioning that Bitbucket released a build status API just recently.

https://blog.bitbucket.org/2015/11/18/introducing-the-build-status-api-for-bitbucket-cloud/

I haven't looked too much into it. I think it will still require that Codeship actually update and integrate with it, but still a step in the right direction for sure.

**Pull request merged**
